drop table if exists competitions_infinitechallengelog;
drop table if exists competitions_pklog;
drop table if exists competitions_studenthascompetitionlog;
drop table if exists study_studentunit;
drop table if exists study_question;
drop table if exists books_examplesentence ;
drop table if exists information_student;
drop table if exists books_classification;
drop table if exists competitions_competitioninfo;
drop table if exists books_unitinfo;
drop table if exists study_wordlog;
drop table if exists study_studentbook;
drop table if exists study_pretestlog;
drop table if exists study_testlog;
drop table if exists study_studylog;
drop table if exists teachers_teacherbuiltin;
drop table if exists information_studentbuiltin;
drop table if exists books_word;
drop table if exists books_category ;
drop table if exists information_classes;
drop table if exists books_edition;
